#!/usr/bin/perl

#
# template-tt - Clockwork Template Toolkit Renderer
#
# author:  Dan Molik <dan@d3fy.net>
# created: 2017-07-26
#

use strict;
use warnings;

use Template;

my $tt = Template->new({EVAL_PERL => 1});
open my $fh, '<', $ARGV[0] or die "unable to open $ARGV[0]: $!";
my $template;
while (<$fh>) {
	$template .= $_;
}
close $fh;
my ($k, $v);
my $data = {};
for (<STDIN>) {
	chomp;
	($k, $v) = split '=', $_;
	$k =~ s/\./_/g;
	$data->{$k} = $v;
}
$tt->process(\$template, $data);

# vim:ft=perl
